manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: dlip
      url-base: https://github.com/dlip
  projects:
    - name: zmk-analog-input-driver
      remote: dlip
      revision: 79ddd37f14781f953235e7ff6fb8cce3685a7048  # main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: 12d532104ff1ef2a91d264a623842ea2095926cc  # main
    - name: zmk
      remote: dlip
      revision: eeac4c3a53e6945281d5e2bb189c94b2c0bbce45  # main
      import: app/west.yml
    - name: zephyr
      remote: zmkfirmware
      revision: 0fa4cc26d8b1e5243570ccc0f7f66c4c428d2961  # v3.5.0+zmk-fixes
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
  self:
    path: config
