manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: 72280acc8e4467ed1b4947ee216c6bf31d0278b2  # main
    - name: zmk
      remote: zmkfirmware
      revision: eb99b4ede06bc01674ce16217ebbad40bc11ec50  # main
      import: app/west.yml
    - name: zephyr
      remote: zmkfirmware
      revision: 489d3b00c49d1d3a0d4ec1f693fa0719db38bbf9  # v3.5.0+zmk-fixes
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
  self:
    path: config
